# Generated by Django 4.2 on 2023-08-20 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawlerRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("jobposts", models.IntegerField(default=0)),
                ("companies", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
