# Generated by Django 4.2 on 2023-08-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlerrecord",
            name="companies",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="crawlerrecord",
            name="jobposts",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
