# Generated by Django 4.2 on 2023-09-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0003_alter_crawlerrecord_options_crawlerrecord_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlerrecord",
            name="categories",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
