[phases.setup]
nixPkgs = [
    'python310',
    'nodejs',
    'postgresql',
    'gcc',
]

[phases.install]
cmds = [
    'python -m venv /opt/venv',
    '. /opt/venv/bin/activate',
    'pip install -r requirements.txt',
    'npm --prefix frontend/ install',
]

[phases.build]
cmds = [
    'npm --prefix frontend/ run generate',
    'python manage.py collectstatic --no-input',
    'python manage.py migrate'
]

[start]
cmd = 'python cron.py & gunicorn backend.config.wsgi'