[phases.setup]
nixPkgs = [
    'python310',
    'nodejs',
    'postgresql',
    'gcc'
]

[phases.install]
cmds = [
    'python -m venv /opt/venv',
    '. /opt/venv/bin/activate',
    'pip install -r requirements.txt',
]

[phases.build]
cmds = [
    'python manage.py collectstatic',
    'python manage.py migrate'
]

[start]
cmd = 'gunicorn backend.config.wsgi'