# Generated by Django 4.2 on 2023-09-02 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobpost", "0004_company_origin_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobpost",
            options={"ordering": ["release_date", "-created_at"]},
        ),
    ]
