# Generated by Django 4.2 on 2023-09-08 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobpost", "0005_alter_jobpost_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["name", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="websiteorigin",
            options={"ordering": ["name", "-created_at"]},
        ),
    ]
