# Generated by Django 4.2 on 2023-09-08 17:32

from django.db import migrations


def extract_data_from_duplicated(original_company, companies):
    for company in companies:
        set_original_company(original_company, company)
        company.delete()

def set_original_company(original_company, company):
    for jobpost in company.jobpost_set.all():
        jobpost.company = original_company
        jobpost.save()

def join_duplicated_companies(apps, schema_editor):
    Company = apps.get_model('jobpost', 'Company')
    websites = Company.objects.order_by().values('website').distinct()

    for data in websites:
        companies = list(Company.objects.filter(website=data['website']).order_by('created_at'))

        if len(companies) < 1:
            continue

        original_company = companies.pop(0)
        extract_data_from_duplicated(original_company, companies)

class Migration(migrations.Migration):
    dependencies = [
        ("jobpost", "0006_alter_category_options_alter_company_options_and_more"),
    ]

    operations = [
        migrations.RunPython(join_duplicated_companies, migrations.RunPython.noop)
    ]
