# Generated by Django 4.2 on 2023-09-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobpost", "0007_join_duplicated_companies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="origin_url",
            field=models.URLField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="websiteorigin",
            name="website",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
