# Generated by Django 4.2 on 2023-09-08 17:32

from django.db import migrations
from django.db.models import Q

def delete_empty_companies(apps, _):
    Company = apps.get_model('jobpost', 'Company')
    
    queryset = Company.objects.filter(
        Q(description__isnull=True)
        | Q(description__exact="")
        | Q(jobpost__isnull=True)
    )

    queryset.delete()
        

class Migration(migrations.Migration):
    dependencies = [
        ("jobpost", "0009_alter_company_website_alter_jobpost_origin_url_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_empty_companies, migrations.RunPython.noop)
    ]
